POST http://localhost:8888/api/store-game
Content-Type: application/x-www-form-urlencoded

user_x=mosh&user_o=jernej

### set username

GET http://localhost:8888/api/empty-positions
Accept: application/json

###


POST http://localhost:8888/api/store-location
game_id=1&positions=11&user_id=mosh

### store location

GET http://localhost:8888/api/list-games?status=COMPLETED
status=ACTIVE/COMPLETED

### get list of all names by status

GET http://localhost:8888/api/read-game?game_id=1
game_id=1

### read game by id
